const MAP = {
  stepforward: { content: "\ue600" },
  stepbackward: { content: "\ue601" },
  forward: { content: "\ue602" },
  banckward: { content: "\ue603" },
  caretright: { content: "\ue604" },
  caretleft: { content: "\ue605" },
  caretdown: { content: "\ue606" },
  caretup: { content: "\ue607" },
  rightcircle: { content: "\ue608" },
  leftcircle: { content: "\ue609" },
  upcircle: { content: "\ue60a" },
  downcircle: { content: "\ue60b" },
  rightcircleo: { content: "\ue60c" },
  leftcircleo: { content: "\ue60d" },
  upcircleo: { content: "\ue60e" },
  downcircleo: { content: "\ue60f" },
  verticleleft: { content: "\ue610" },
  verticleright: { content: "\ue611" },
  back: { content: "\ue612" },
  retweet: { content: "\ue613" },
  shrink: { content: "\ue614" },
  arrowsalt: { content: "\ue615" },
  doubleright: { content: "\ue617" },
  doubleleft: { content: "\ue618" },
  arrowdown: { content: "\ue619" },
  arrowup: { content: "\ue61a" },
  arrowright: { content: "\ue61b" },
  arrowleft: { content: "\ue61c" },
  down: { content: "\ue61d" },
  up: { content: "\ue61e" },
  right: { content: "\ue61f" },
  left: { content: "\ue620" },
  minussquareo: { content: "\ue621" },
  minuscircle: { content: "\ue622" },
  minuscircleo: { content: "\ue623" },
  minus: { content: "\ue624" },
  pluscircleo: { content: "\ue625" },
  pluscircle: { content: "\ue626" },
  plus: { content: "\ue627" },
  infocirlce: { content: "\ue628" },
  infocirlceo: { content: "\ue629" },
  info: { content: "\ue62a" },
  exclamation: { content: "\ue62b" },
  exclamationcircle: { content: "\ue62c" },
  exclamationcircleo: { content: "\ue62d" },
  closecircle: { content: "\ue62e" },
  closecircleo: { content: "\ue62f" },
  checkcircle: { content: "\ue630" },
  checkcircleo: { content: "\ue631" },
  check: { content: "\ue632" },
  close: { content: "\ue633" },
  customerservice: { content: "\ue634" },
  creditcard: { content: "\ue635" },
  codesquareo: { content: "\ue636" },
  book: { content: "\ue637" },
  barschart: { content: "\ue638" },
  bars: { content: "\ue639" },
  question: { content: "\ue63a" },
  questioncircle: { content: "\ue63b" },
  questioncircleo: { content: "\ue63c" },
  pause: { content: "\ue63d" },
  pausecircle: { content: "\ue63e" },
  pausecircleo: { content: "\ue63f" },
  clockcircle: { content: "\ue640" },
  clockcircleo: { content: "\ue641" },
  swap: { content: "\ue642" },
  swapleft: { content: "\ue643" },
  swapright: { content: "\ue644" },
  plussquareo: { content: "\ue645" },
  frown: { content: "\ue646" },
  menufold: { content: "\ue658" },
  mail: { content: "\ue659" },
  link: { content: "\ue65b" },
  areachart: { content: "\ue65c" },
  linechart: { content: "\ue65d" },
  home: { content: "\ue65e" },
  laptop: { content: "\ue65f" },
  star: { content: "\ue660" },
  staro: { content: "\ue661" },
  filter: { content: "\ue663" },
  meho: { content: "\ue666" },
  meh: { content: "\ue667" },
  shoppingcart: { content: "\ue668" },
  save: { content: "\ue669" },
  user: { content: "\ue66a" },
  videocamera: { content: "\ue66b" },
  totop: { content: "\ue66c" },
  team: { content: "\ue66d" },
  sharealt: { content: "\ue671" },
  setting: { content: "\ue672" },
  picture: { content: "\ue674" },
  phone: { content: "\ue675" },
  paperclip: { content: "\ue676" },
  notification: { content: "\ue677" },
  menuunfold: { content: "\ue679" },
  inbox: { content: "\ue67a" },
  lock: { content: "\ue67b" },
  qrcode: { content: "\ue67c" },
  tags: { content: "\ue67d" },
  tagso: { content: "\ue67e" },
  cloudo: { content: "\ue67f" },
  cloud: { content: "\ue680" },
  cloudupload: { content: "\ue681" },
  clouddownload: { content: "\ue682" },
  clouddownloado: { content: "\ue683" },
  clouduploado: { content: "\ue684" },
  environment: { content: "\ue685" },
  environmento: { content: "\ue686" },
  eye: { content: "\ue687" },
  eyeo: { content: "\ue688" },
  camera: { content: "\ue689" },
  camerao: { content: "\ue68a" },
  windows: { content: "\ue68b" },
  export2: { content: "\ue690" },
  export: { content: "\ue691" },
  circledowno: { content: "\ue693" },
  circledown: { content: "\ue694" },
  hdd: { content: "\ue69a" },
  ie: { content: "\ue69b" },
  delete: { content: "\ue69f" },
  enter: { content: "\ue6a0" },
  pushpino: { content: "\ue6a1" },
  pushpin: { content: "\ue6a2" },
  heart: { content: "\ue6a3" },
  hearto: { content: "\ue6a4" },
  "smile-circle": { content: "\ue6a7" },
  smileo: { content: "\ue6a8" },
  frowno: { content: "\ue6a9" },
  calculator: { content: "\ue6aa" },
  chrome: { content: "\ue6ac" },
  github: { content: "\ue6ad" },
  iconfontdesktop: { content: "\ue6b4" },
  caretcircleoup: { content: "\ue6b5" },
  upload: { content: "\ue6b6" },
  download: { content: "\ue6b7" },
  piechart: { content: "\ue6b8" },
  lock1: { content: "\ue6b9" },
  unlock: { content: "\ue6ba" },
  windowso: { content: "\ue6bc" },
  dotchart: { content: "\ue6bd" },
  barchart: { content: "\ue6be" },
  codesquare: { content: "\ue6bf" },
  plussquare: { content: "\ue6c0" },
  minussquare: { content: "\ue6c1" },
  closesquare: { content: "\ue6c2" },
  closesquareo: { content: "\ue6c3" },
  checksquare: { content: "\ue6c4" },
  checksquareo: { content: "\ue6c5" },
  fastbackward: { content: "\ue6c6" },
  fastforward: { content: "\ue6c7" },
  upsquare: { content: "\ue6c8" },
  downsquare: { content: "\ue6c9" },
  leftsquare: { content: "\ue6ca" },
  rightsquare: { content: "\ue6cb" },
  rightsquareo: { content: "\ue6cc" },
  leftsquareo: { content: "\ue6cd" },
  "down-square-o": { content: "\ue6ce" },
  "up-square-o": { content: "\ue6cf" },
  play: { content: "\ue6d0" },
  playcircleo: { content: "\ue6d1" },
  tag: { content: "\ue6d2" },
  tago: { content: "\ue6d3" },
  addfile: { content: "\ue910" },
  folder1: { content: "\ue662" },
  file1: { content: "\ue664" },
  switcher: { content: "\ue913" },
  addfolder: { content: "\ue914" },
  folderopen: { content: "\ue699" },
  search: { content: "\ue670" },
  ellipsis1: { content: "\ue647" },
  calendar: { content: "\ue6bb" },
  filetext: { content: "\ue698" },
  copy1: { content: "\ue648" },
  jpgfile1: { content: "\ue69c" },
  pdffile1: { content: "\ue6b3" },
  exclefile1: { content: "\ue6b0" },
  pptfile1: { content: "\ue6b1" },
  unknowfile1: { content: "\ue6af" },
  wordfile1: { content: "\ue6b2" },
  dingding: { content: "\ue923" },
  "dingding-o": { content: "\ue925" },
  mobile1: { content: "\ue678" },
  tablet1: { content: "\ue66e" },
  bell: { content: "\ue64e" },
  disconnect: { content: "\ue64f" },
  database: { content: "\ue650" },
  barcode: { content: "\ue652" },
  hourglass: { content: "\ue653" },
  key: { content: "\ue654" },
  flag: { content: "\ue655" },
  layout: { content: "\ue656" },
  printer: { content: "\ue673" },
  USB: { content: "\ue6d7" },
  skin: { content: "\ue6d8" },
  tool: { content: "\ue6d9" },
  car: { content: "\ue6dc" },
  addusergroup: { content: "\ue6dd" },
  carryout: { content: "\ue6df" },
  deleteuser: { content: "\ue6e0" },
  deleteusergroup: { content: "\ue6e1" },
  man: { content: "\ue6e2" },
  isv: { content: "\ue6e3" },
  gift: { content: "\ue6e4" },
  idcard: { content: "\ue6e5" },
  medicinebox: { content: "\ue6e6" },
  redenvelopes: { content: "\ue6e7" },
  rest: { content: "\ue6e8" },
  Safety: { content: "\ue6ea" },
  wallet: { content: "\ue6eb" },
  woman: { content: "\ue6ec" },
  adduser: { content: "\ue6ed" },
  bank: { content: "\ue6ee" },
  Trophy: { content: "\ue6ef" },
  loading1: { content: "\ue6ae" },
  loading2: { content: "\ue64d" },
  like: { content: "\ue69d" },
  dislike2: { content: "\ue69e" },
  like1: { content: "\ue64c" },
  dislike1: { content: "\ue64b" },
  bulb1: { content: "\ue649" },
  rocket1: { content: "\ue90f" },
  select1: { content: "\ue64a" },
  apple1: { content: "\ue68c" },
  "apple-o": { content: "\ue6d4" },
  android1: { content: "\ue938" },
  android: { content: "\ue68d" },
  "aliwangwang-o1": { content: "\ue68f" },
  aliwangwang: { content: "\ue68e" },
  "pay-circle1": { content: "\ue6a5" },
  "pay-circle-o1": { content: "\ue6a6" },
  poweroff: { content: "\ue6d5" },
  trademark: { content: "\ue651" },
  find: { content: "\ue6db" },
  copyright: { content: "\ue6de" },
  sound: { content: "\ue6e9" },
  earth: { content: "\ue6f1" },
  wifi: { content: "\ue6d6" },
  sync: { content: "\ue6da" },
  login: { content: "\ue657" },
  logout: { content: "\ue65a" },
  reload1: { content: "\ue616" },
  message1: { content: "\ue6ab" },
  shake: { content: "\ue94f" },
  API: { content: "\ue951" },
  "appstore-o": { content: "\ue695" },
  appstore1: { content: "\ue696" },
  scan1: { content: "\ue697" },
  exception1: { content: "\ue665" },
  contacts: { content: "\ue6f0" },
  solution1: { content: "\ue66f" },
  fork: { content: "\ue6f2" },
  edit: { content: "\ue692" },
  form: { content: "\ue996" },
  warning: { content: "\ue997" },
  table: { content: "\ue998" },
  profile: { content: "\ue999" },
  dashboard: { content: "\ue99a" },
  "indent-left": { content: "\ue9a6" },
  "indent-right": { content: "\ue9a7" },
  "menu-unfold": { content: "\ue9ac" },
  "menu-fold": { content: "\ue9ad" },
  antdesign: { content: "\ue9b2" },
  "alipay-square": { content: "\ue9b3" },
  "codepen-circle": { content: "\ue9b4" },
  google: { content: "\ue9b5" },
  amazon: { content: "\ue9b6" },
  codepen: { content: "\ue9b7" },
  "facebook-square": { content: "\ue9b8" },
  dropbox: { content: "\ue9b9" },
  googleplus: { content: "\ue9ba" },
  "linkedin-square": { content: "\ue9bb" },
  "medium-monogram": { content: "\ue9bc" },
  gitlab: { content: "\ue9bd" },
  "medium-wordmark": { content: "\ue9be" },
  QQ: { content: "\ue9bf" },
  skype: { content: "\ue9c0" },
  "taobao-square": { content: "\ue9c1" },
  "alipay-circle": { content: "\ue9c2" },
  youtube: { content: "\ue9c3" },
  wechat: { content: "\ue9c4" },
  twitter: { content: "\ue9c5" },
  weibo: { content: "\ue9c6" },
  HTML: { content: "\ue9c7" },
  "taobao-circle": { content: "\ue6f3" },
  "weibo-circle": { content: "\ue6f4" },
  "weibo-square": { content: "\ue6f5" },
  CodeSandbox: { content: "\ue9d4" },
  aliyun: { content: "\ue9f4" },
  zhihu: { content: "\ue703" },
  behance: { content: "\ue707" },
  dribbble: { content: "\ue709" },
  "dribbble-square": { content: "\ue70a" },
  "behance-square": { content: "\ue708" },
  "file-markdown": { content: "\ue704" },
  instagram: { content: "\ue70b" },
  yuque: { content: "\ue70c" },
  slack: { content: "\ue705" },
  "slack-square": { content: "\ue706" },
  // icon
  "village-close-circle": { content: "\ue65a" },

  "village-tick": { content: "\ue78b" },

  "village-more": { content: "\ue634" },

  "village-people": { content: "\ue637" },

  "village-time": { content: "\ue63e" },

  "village-location-circle-o": { content: "\ue651" },

  "village-video-o": { content: "\ue81c" },

  "village-mine-o": { content: "\ue658" },

  "village-news-o": { content: "\ue659" },

  "village-message": { content: "\ue611" },

  "village-feedback": { content: "\ue612" },

  "village-personal-center": { content: "\ue613" },

  "village-warning": { content: "\ue614" },

  "village-system-settings": { content: "\ue616" },

  "village-exit": { content: "\ue617" },

  "village-clothes": { content: "\ue61a" },

  "village-car": { content: "\ue8aa" },

  "village-phone": { content: "\ue8ab" },

  "village-maintenance": { content: "\ue8ad" },

  "village-around": { content: "\ue8ae" },

  "village-water-pipe": { content: "\ue8af" },

  "village-service": { content: "\ue8b0" },

  "village-location-o": { content: "\ue8b1" },

  "village-sofa-cleaning": { content: "\ue8b3" },

  "village-text-o": { content: "\ue8b4" },

  "village-scanning": { content: "\ue8b8" },

  "village-Serial-number-copy-copy": { content: "\ue8b9" },

  "village-order-center": { content: "\ue65b" },

  "village-bill-invoice-o-copy": { content: "\ue8ba" },

  "village-help-use-book-o-copy": { content: "\ue8bb" },

  "village-home-add-copy": { content: "\ue8bc" },

  "village-nav_back-copy": { content: "\ue8bd" },

  "village-icon-close-copy": { content: "\ue8be" },

  "village-choice-o-copy": { content: "\ue8bf" },

  "village-choice-copy": { content: "\ue8c0" },

  "village-Homepage1-copy": { content: "\ue8c1" },

  "village-help-use-book-o-copy1": { content: "\ue8c2" },

  "village-me_contact-copy": { content: "\ue8c3" },

  "village-logo-copy": { content: "\ue8c4" },

  "village-me-serve": { content: "\ue8c5" },

  "village-order-center-o": { content: "\ue66a" },

  "village-around-o": { content: "\ue66c" },

  "village-mine": { content: "\ue66d" },

  "village-order-number": { content: "\ue8c7" },

  "village-total-circle-o": { content: "\ue630" },

  "village-people-tab-o": { content: "\ue66f" },

  "village-people-tab": { content: "\ue672" },

  "village-video": { content: "\ue673" },

  "village-video-o1": { content: "\ue674" },

  "village-qr-code": { content: "\ue675" },

  "village-around1": { content: "\ue67b" },

  "village-news": { content: "\ue67c" },

  "village-plane": { content: "\ue67e" },

  "village-face-recognition": { content: "\ue67f" },

  "village-download": { content: "\ue682" },

  "village-share": { content: "\ue683" },

  "village-record": { content: "\ue685" },

  "village-photo-album": { content: "\ue686" },

  "village-video-play": { content: "\ue688" },

  "village-serveing-compass": { content: "\ue689" },

  "village-location-point-red": { content: "\ue68b" },

  "village-profile-photo": { content: "\ue68d" },
};

export default MAP;
